import React from 'react';

const TermsOfService: React.FC = () => {
    return (
        <div className="bg-gray-50 py-12">
            <div className="container mx-auto px-6 max-w-4xl bg-white p-8 md:p-12 rounded-lg shadow-md">
                <article className="prose lg:prose-xl max-w-none text-gray-700">
                    <h1 className="text-4xl font-bold text-gray-900 mb-4">Terms of Service</h1>
                    <p className="text-sm text-gray-500">Last updated: {new Date().toLocaleDateString()}</p>

                    <h2 className="text-2xl font-bold text-gray-800 mt-8">1. Acceptance of Terms</h2>
                    <p>
                        By accessing and using AI Bank Statement Converter (the "Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this Service.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-800 mt-8">2. Description of Service</h2>
                    <p>
                        The Service provides users with a tool to convert bank statements from various formats (PDF, images) into structured data formats like CSV or Excel. This is achieved by using third-party AI models (Google Gemini API). The Service also provides an in-browser utility to unlock password-protected PDF files.
                    </p>
                    
                    <h2 className="text-2xl font-bold text-gray-800 mt-8">3. User Responsibilities</h2>
                    <ul>
                        <li>You must have the legal right to access and process any documents you upload to the Service.</li>
                        <li>You agree not to use the Service for any illegal or unauthorized purpose.</li>
                        <li>You are responsible for the confidentiality and security of your own documents.</li>
                    </ul>

                    <h2 className="text-2xl font-bold text-gray-800 mt-8">4. Disclaimers and Limitation of Liability</h2>
                    <p>
                        <strong>No Guarantee of Accuracy:</strong> The Service relies on AI models, which may make mistakes. We do not guarantee the accuracy, completeness, or reliability of any data extracted or generated by the Service. You must verify the accuracy of the output before relying on it for any purpose, including financial, accounting, or legal decisions.
                    </p>
                    <p>
                        <strong>As-Is Service:</strong> The Service is provided "as is" and "as available" without any warranties of any kind, express or implied.
                    </p>
                    <p>
                        <strong>Limitation of Liability:</strong> In no event shall AI Bank Statement Converter, its owners, or affiliates be liable for any direct, indirect, incidental, special, consequential, or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data, or other intangible losses resulting from the use of or inability to use the service.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-800 mt-8">5. Third-Party Services</h2>
                    <p>
                        The Service integrates with the Google Gemini API. Your use of the core conversion feature is subject to Google's terms and policies. We are not responsible for the data processing or availability of third-party services.
                    </p>

                    <h2 className="text-2xl font-bold text-gray-800 mt-8">6. Changes to Terms</h2>
                     <p>
                        We reserve the right to modify these terms from time to time at our sole discretion. Therefore, you should review this page periodically. Your continued use of the Website or our service after any such change constitutes your acceptance of the new Terms.
                    </p>
                </article>
            </div>
        </div>
    );
};

export default TermsOfService;
